Added basic version and upgrade scripts

diff --git a/apic/install b/apic/install
--- a/apic/install
+++ b/apic/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Install master devstack with APIC ML2 driver for neutron
+# Install icehouse devstack with APIC ML2 driver for neutron
 #
 
 # Usage:
@@ -13,9 +13,7 @@ APIC_IP_ADDR=$1
 APIC_PORT='80'
 APIC_CONFIG='/etc/neutron/plugins/ml2/ml2_cisco_conf.ini'
 DEVSTACK_REPO='https://github.com/noironetworks/devstack.git'
-DEVSTACK_BRANCH='cisco-apic-master'
-STACK_HOME='/opt/stack'
-DEVSTACK_TOP="${STACK_HOME}/devstack"
+DEVSTACK_BRANCH='cisco-apic-icehouse'
 CREATED_USER=false
 
 # Validate args
@@ -32,9 +30,10 @@ if [ ! -f /etc/lsb-release ] ; then
 fi
 eval `cat /etc/lsb-release`
 if [ "${DISTRIB_RELEASE}"x != "12.04"x ] ; then
-    echo "WARNING: This script has only been tested on ubuntu 12.04" 1>&2
+    echo "ERROR: This script is only supported on ubuntu 12.04" 1>&2
+    exit 1
 fi
-if [ -d ${DEVSTACK_TOP} ] ; then
+if [ -d /opt/stack/devstack ] ; then
     echo "ERROR: devstack already exists" 1>&2
     exit 1
 fi
@@ -42,7 +41,7 @@ fi
 # install git
 sudo apt-get -y update
 sudo apt-get -y upgrade
-sudo apt-get -y install python-all-dev python-pip python-mysqldb git
+sudo apt-get -y install python-all-dev python-pip git
 
 # Create user 'stack' if one already does not exist, and
 #  - set same ssh privilages as current user
@@ -55,11 +54,9 @@ fi
 if ! sudo egrep '^stack:' /etc/passwd 1>/dev/null
 then
     CREATED_USER=true
-    sudo useradd -g stack -s /bin/bash -d ${STACK_HOME} -m stack
-    if [ -d "${HOME}/.ssh" ] ; then
-        sudo cp -r ${HOME}/.ssh ${STACK_HOME}/.ssh
-        sudo chown -R stack.stack ${STACK_HOME}/.ssh
-    fi
+    sudo useradd -g stack -s /bin/bash -d /opt/stack -m stack
+    sudo cp -r ${HOME}/.ssh /opt/stack/.ssh
+    sudo chown -R stack.stack /opt/stack/.ssh
 fi
 
 if ! sudo egrep 'stack\ ALL' /etc/sudoers 1>/dev/null
@@ -68,14 +65,13 @@ then
 fi
 
 # Install devstack, always download the repo again
-sudo chmod a+w ${STACK_HOME}
-git clone -b ${DEVSTACK_BRANCH} ${DEVSTACK_REPO} ${DEVSTACK_TOP}
+sudo chmod a+w /opt/stack
+git clone -b ${DEVSTACK_BRANCH} ${DEVSTACK_REPO} /opt/stack/devstack
 
 # create sample local.conf files
-cat >${DEVSTACK_TOP}/local.conf.ctrl-node <<EOF
+cat >/opt/stack/devstack/local.conf.ctrl-node <<EOF
 [[local|localrc]]
-ENABLED_SERVICES=g-api,g-reg,key,n-api,n-crt,n-obj,n-cpu,n-cond,n-sch,n-novnc,n-cauth,horizon,rabbit,neutron,q-svc,q-agt,q-dhcp,quantum,mysql,q-meta,cisco_apic,apicagt,apicsvc
-IMAGE_URLS="http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-uec.tar.gz,http://cloud-images.ubuntu.com/releases/precise/release/ubuntu-12.04-server-cloudimg-amd64-disk1.img"
+ENABLED_SERVICES=g-api,g-reg,key,n-api,n-crt,n-obj,n-cpu,n-cond,n-sch,n-novnc,n-cauth,horizon,rabbit,neutron,q-svc,q-agt,q-dhcp,quantum,mysql,q-meta
 
 MULTI_HOST=1
 HOST_IP=${HOST_IP_ADDR}
@@ -101,18 +97,16 @@ RABBIT_PASSWORD=supersecret
 SERVICE_PASSWORD=supersecret
 SERVICE_TOKEN=xyzlazydog
 
-LOGFILE=${STACK_HOME}/logs/stack.sh.log
-SCREEN_LOGDIR=${STACK_HOME}/logs
+LOGFILE=/opt/stack/logs/stack.sh.log
+SCREEN_LOGDIR=/opt/stack/logs
 #VERBOSE=True
 #DEBUG=True
 #OFFLINE=True
-#RECLONE=yes
 EOF
 
-cat >${DEVSTACK_TOP}/local.conf.ctrl-noapic <<EOF
+cat >/opt/stack/devstack/local.conf.ctrl-noapic <<EOF
 [[local|localrc]]
 ENABLED_SERVICES=g-api,g-reg,key,n-api,n-crt,n-obj,n-cpu,n-cond,n-sch,n-novnc,n-cauth,horizon,rabbit,neutron,q-svc,q-agt,q-dhcp,quantum,mysql,q-meta,q-l3
-IMAGE_URLS="http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-uec.tar.gz,http://cloud-images.ubuntu.com/releases/precise/release/ubuntu-12.04-server-cloudimg-amd64-disk1.img"
 
 MULTI_HOST=1
 HOST_IP=${HOST_IP_ADDR}
@@ -135,18 +129,16 @@ RABBIT_PASSWORD=supersecret
 SERVICE_PASSWORD=supersecret
 SERVICE_TOKEN=xyzlazydog
 
-LOGFILE=${STACK_HOME}/logs/stack.sh.log
-SCREEN_LOGDIR=${STACK_HOME}/logs
+LOGFILE=/opt/stack/logs/stack.sh.log
+SCREEN_LOGDIR=/opt/stack/logs
 #VERBOSE=True
 #DEBUG=True
 #OFFLINE=True
-#RECLONE=yes
 EOF
 
-cat >${DEVSTACK_TOP}/local.conf.compute-node <<EOF
+cat >/opt/stack/devstack/local.conf.compute-node <<EOF
 [[local|localrc]]
-ENABLED_SERVICES=n-cpu,q-agt,n-novnc,rabbit,neutron,nova,cisco_apic,apicagt
-IMAGE_URLS="http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-uec.tar.gz,http://cloud-images.ubuntu.com/releases/precise/release/ubuntu-12.04-server-cloudimg-amd64-disk1.img"
+ENABLED_SERVICES=n-cpu,q-agt,n-novnc,rabbit,neutron,nova
 
 MULTI_HOST=1
 HOST_IP=${HOST_IP_ADDR}
@@ -172,36 +164,23 @@ RABBIT_PASSWORD=supersecret
 SERVICE_PASSWORD=supersecret
 SERVICE_TOKEN=xyzlazydog
 
-LOGFILE=${STACK_HOME}/logs/stack.sh.log
-SCREEN_LOGDIR=${STACK_HOME}/logs
+LOGFILE=/opt/stack/logs/stack.sh.log
+SCREEN_LOGDIR=/opt/stack/logs
 #VERBOSE=True
 #DEBUG=True
 #OFFLINE=True
-#RECLONE=yes
 EOF
-
-cat >${DEVSTACK_TOP}/local.sh <<EOF
-#!/bin/bash
-[ -f  ${DEVSTACK_TOP}/.localrc.auto ] && . ${DEVSTACK_TOP}/.localrc.auto
-export MYSQL_PASSWORD
-[ -n "\$SERVICE_HOST" ] && export SERVICE_HOST
-${DEVSTACK_TOP}/apic/check_agents
-EOF
-chmod a+x ${DEVSTACK_TOP}/local.sh
-
-cp ${DEVSTACK_TOP}/local.conf.ctrl-node ${DEVSTACK_TOP}/local.conf
-sudo chmod go-w ${STACK_HOME}
-sudo chown -R stack.stack ${STACK_HOME}
+cp /opt/stack/devstack/local.conf.ctrl-node /opt/stack/devstack/local.conf
+sudo chmod go-w /opt/stack
+sudo chown -R stack.stack /opt/stack
 
 # Update config in /etc
 sudo mkdir -p /etc/neutron/plugins/ml2
 sudo tee /etc/neutron/plugins/ml2/ml2_conf_cisco.ini 1>/dev/null <<EOF
-[DEFAULT]
-apic_system_id=openstack1
-
 [ml2_cisco_apic]
+
 # Hostname for the APIC controller
-apic_hosts=${APIC_IP_ADDR}
+apic_host=${APIC_IP_ADDR}
 
 # Username for the APIC controller
 apic_username=admin
@@ -209,18 +188,27 @@ apic_username=admin
 # Password for the APIC controller
 apic_password=password
 
+# Port for the APIC Controller
+apic_port=80
+
 # How to map names to APIC: use_uuid or use_name
 apic_name_mapping=use_name
 
-# For testing only
+# Default names in APIC policies
+apic_vmm_provider=VMware
+apic_vmm_domain=openstack
+apic_app_profile_name=openstack_app
+apic_vlan_ns_name=openstack_ns
+apic_node_profile=openstack_profile
+apic_entity_profile=openstack_entity
+apic_function_profile=openstack_function
 apic_clear_node_profiles=True
 
-# For static configuration, by default detect hostlinks
-# [apic_switch:17]
-# compute01=1/17
-#
-# [apic_switch:18]
-# compute02=1/17
+[apic_switch:17]
+compute01=1/17
+
+[apic_switch:18]
+compute02=1/17
 EOF
 sudo chown -R stack.stack /etc/neutron
 
